Interactivecv.Job = DS.Model.extend
  title: DS.attr('string')
  company: DS.attr('string')
  location: DS.attr('string')
  description: DS.attr('string')
  startDate: DS.attr('date')
  endDate: DS.attr('date')
  content_images: DS.hasMany('Interactivecv.ContentImage')
  lead_image_id: DS.attr('number')
  skills: DS.hasMany('Interactivecv.Skill')
